name: tests

on: [push]

jobs:
  react:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: node_modules Cache
        id: node-modules-test-cache
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/node_modules
          key: ${{ runner.os }}-node-modules
      - name: node_modules Restore Cache
        if: steps.node-modules-test-cache.outputs.cache-hit == 'true'
        env:
          SOURCE: ${{ runner.temp }}/node_modules
        run: cp -r --force -v ${SOURCE} ./node_modules
      - name: Install Node dependencies
        run: |
          npm ci
          cp -r --force ./node_modules ${{ runner.temp }}/node_modules
      - name: Run React tests
        run: npm test -- --coverage .
